### PR TITLE
Add a simple numpy datetime64 compatibility shim

### PR DESCRIPTION
**Pull request by jameshilliard**
I think numpy(which is a huge library) is a bit overkill for what seems to be a small subset of `datetime64` functionality, we can just add a small shim class for the parts we need(seems to mostly just be nanosecond precision `datetime64` object serialization/deserialization functionality).

### CODE REVIEW

**Comment by oberstet** [comment]
> for what seems to be a small subset of datetime64 functionality

zlmdb also supports numpy arrays for value types of tables, and it supports the use of numpy arrays for flatbuffers. both of these features are used in cfxdb - which in turn is what crossbar depends on.

so if you only look at zlmdb, and general users of zlmdb in itself, it probably makes sense to have one or more "install flavors", similar what autobahn does, to allow to select with/without numpy, and with/without flatbuffers

if you only care about zlmdb as a crossbar dependency: sorry, nope, cfxdb and use of numpy arrays is a deliberate, conscious design choice .. I mean, we considered the price to pay: having numpy as a dependency.

-----

rgd your PR: this looks pretty good based on a goal of "zlmdb numpy-less install flavor" .. however, I'm not sure about your goals (what I hinted above). also, rgd the CI: this has run green ... but it won't work with cfxdb (won't run green), and also won't work for crossbar ...

**Comment by oberstet** [comment]
for an example how crossbar uses this stuff, consider this wrapper database class for persistent realm stores:

https://github.com/crossbario/cfxdb/blob/3acbf87caaaa89eabe631c44ca7377b66bd5ce28/cfxdb/realmstore/_session.py#L128

even only this datetime example would require more work, but it could be made working. however, the whole database table is using flatbuffers values, and flatbuffers requires numpy as well

https://github.com/crossbario/cfxdb/blob/3acbf87caaaa89eabe631c44ca7377b66bd5ce28/cfxdb/gen/realmstore/Session.py#L7

-----

as a second example, consider this (from a crossbar based app):

```
/// Current and history of order book (Level II Market Data) as resulting from applying all updates sent by the exchange in a live feed.
table Orderbook
{
    /// Period to which the orderbook record applies for, using PeriodDuration.NOW for the current orderbook (within the current yet unfinished period). [primary key]
    period_dur: PeriodDuration;

    /// Database object ID of the market this orderbook applies for, e.g. "ETH-USD-PERP on dYdX". [primary key]
    market_oid: [uint8] (uuid);

    /// Last update for current orderbook or start time of period for order book history (epoch time in ns). [primary key]
    start_ts: uint64 (timestamp);

    /// ASKS (aka "offers") from LIMIT orders (valid and unfilled at the END of the respective period) for base asset ordered ascending by price in QUOTE ticks of asset. MARKET orders to BUY the base asset are hitting the best asks and paid by the aggressor in quote asset.
    asks_price: [uint32];

    /// Quantity (interest) at respective ASK price in steps of BASE asset. The elements in the array are ordered identically and correspond to the ask prices.
    asks_size: [uint32];
...
```


```python
    @property
    def asks_price(self) -> npt.NDArray[np.uint32]:
        """
        ASKS (aka "offers") from LIMIT orders (valid and unfilled at the END of the respective period) for base asset
        ordered ascending by price in QUOTE ticks of asset. MARKET orders to BUY the base asset are hitting the
        best asks and paid by the aggressor in quote asset.
        """
        if self._asks_price is None and self._from_fbs and not self._from_fbs.AsksPriceIsNone():
            self._asks_price = self._from_fbs.AsksPriceAsNumpy()
        return self._asks_price

    @asks_price.setter
    def asks_price(self, value: npt.NDArray[np.uint32]):
        assert value is None or isinstance(value, np.ndarray)
        self._asks_price = value
```


as you can see, this is using a database table that exposes native numpy arrays `npt.NDArray[np.uint32]`, with the data memory mapped directly from disk ... which is super fast, and quite cool;)

----

what I am trying to say is: replacing datetime64 isn't enough .. if we only had had a need for some "timestamp" type, we would never have added numpy, but just used plain python stdlib ...

**Comment by oberstet** [comment]
fwiw, rgd my last example, probably easier/nicer to read, here is the docs for that db table, which as noted is used in a crossbar/autobahn based app. the cool part that one can do numpy analytics directly on the mmap'ed zlmdb tables using native numpy types .. anyways, just to motivate this apparent excessive choice of numpy as a dependency

Bildschirmfoto von 2022-05-12 13-51-41

**Comment by jameshilliard** [comment]
> if you only care about zlmdb as a crossbar dependency: sorry, nope, cfxdb and use of numpy arrays is a deliberate, conscious design choice

I'm not seeing numpy arrays being used anywhere in crossbar or its dependency tree(at least for the public versions), maybe I'm missing something though, from what I can tell `datetime64` is the main blocker for making numpy optional here for zlmdb, cfxdb and crossbar. If numpy is actually needed for some private apps they should be able to pull it in as needed.

> for an example how crossbar uses this stuff, consider this wrapper database class for persistent realm stores:
>
> https://github.com/crossbario/cfxdb/blob/3acbf87caaaa89eabe631c44ca7377b66bd5ce28/cfxdb/realmstore/_session.py#L128

I think should be able to just replace that with the `datetime64` class I wrote in #55.

I'll do some tests to see if there's any issues with using the approach in #55 with cfxdb.

> even only this datetime example would require more work, but it could be made working. however, the whole database table is using flatbuffers values, and flatbuffers requires numpy as well
>
> https://github.com/crossbario/cfxdb/blob/3acbf87caaaa89eabe631c44ca7377b66bd5ce28/cfxdb/gen/realmstore/Session.py#L7

That seems to just be an opportunistic import, from what I can tell it's not actually used in that file.

> flatbuffers requires numpy as well

I think there are non-numpy native equivalents for most operations including arrays.

> this is using a database table that exposes native numpy arrays `npt.NDArray[np.uint32]`, with the data memory mapped directly from disk ... which is super fast, and quite cool

Seems avoiding numpy [may be faster](https://github.com/crossbario/zlmdb/pull/55), especially on pypy where numpy tends to be a performance footgun. Python has some native memory mapping equivalents that works reasonably well from what I can tell.

**Comment by oberstet** [comment]
upfront, thanks a lot for explaining your thinking, feedback and your work! feeling bad, as you obviously spent some time on it, and the PRs look carefully written and such ... buuut ...

> I think there are non-numpy native equivalents for most operations including arrays.

yes, "arrays" and operations on those are built into plain python. but rgd the numpy "operations" in general, honestly, I doubt that. the ecosystem on top of np arrays is huuuge ... from scipy to pyro. the ecosystem on top of Fortran arrays is probably still larger ..

> Seems avoiding numpy https://github.com/crossbario/zlmdb/pull/55, especially on pypy where numpy tends to be a performance footgun.

One can use native numpy arrays not only from pypy (yes, for naive code, this can be a small amount slower than - a recent version of - cpython. I've seen that too), with native code (eg from C++) or automatically JIT'ed code from Numba including SIMD vectorization. I've done benchmarking on this, but would need to dig out the stuff ..

anyways: we will not merge any removal of numpy from crossbar dependencies, and we want to expand and move all crossbar internal tables to Flatbuffers values based zlmdb tables. I'm sorry for the work you did .. well, with an intent to get it merged (obviously, you can use your code as you like ..). had you first posted a new issue "Remove/replace numpy" in crossbar, we could have discussed upfront! so I'm only feeling partially bad:(

In general, also feeling bad because yes, I understand this choice might seem weird, but it is a deliberate, conscious, strategic choice - from _crossbar_ mainly. As is the use of Flatbuffers and LMDB. The combination of Flatbuffers and LMDB fits perfectly what we need and want to do in crossbar rgd "persistent data", and the use of Numpy arrays opens up a world to directly and efficiently analyze such data further down the line (within crossbar itself, even though there isn't yet much analytical stuff in crossbar - _and_ in applications).

In the end, this is all OSS and forkable, and WAMP is open, means there are other good routers of course! without numpy.

Btw: similar discussions can be had over Flatbuffers vs X or Y, and LMDB vs A or B. That's perfectly fine, and there are very good X, Y and A, B, no question, it all depends. For crossbar, Flatbuffers+LMDB+Numpy is perfect in what crossbar needs, but of course there is a price.

**Comment by jameshilliard** [comment]
> As is the use of Flatbuffers and LMDB. The combination of Flatbuffers and LMDB fits perfectly what we need and want to do in crossbar rgd "persistent data", and the use of Numpy arrays opens up a world to directly and efficiently analyze such data further down the line (within crossbar itself, even though there isn't yet much analytical stuff in crossbar - _and_ in applications).

I'm still not sure where there's actually a numpy array required for using crossbar, I mean crossbar so far [seems to work without numpy](https://github.com/crossbario/crossbar/compare/master...jameshilliard:datetime64). Really all I needed to do was go through crossbars dependencies like [`cfxdb`](https://github.com/jameshilliard/cfxdb/tree/datetime64) and [`autobahn-python`](https://github.com/jameshilliard/autobahn-python/tree/datetime64) and swap out `numpy.datetime64` with [`zlmdb.datetime64`](https://github.com/crossbario/zlmdb/pull/55)

> One can use native numpy arrays not only from pypy (yes, for naive code, this can be a small amount slower than - a recent version of - cpython. I've seen that too), with native code (eg from C++) or automatically JIT'ed code from Numba including SIMD vectorization. I've done benchmarking on this, but would need to dig out the stuff ..
>
> anyways: we will not merge any removal of numpy from crossbar dependencies, and we want to expand and move all crossbar internal tables to Flatbuffers values based zlmdb tables. I'm sorry for the work you did .. well, with an intent to get it merged (obviously, you can use your code as you like ..). had you first posted a new issue "Remove/replace numpy" in crossbar, we could have discussed upfront! so I'm only feeling partially bad:(

The changes in #55 aren't really even array related, it's just a simple uint64 data type class swap out for the timestamp. Flatbuffers and zlmdb appear to behave the same effectively with my non-numpy `datetime64` class since the underlying type is just a simple uint64, unless I've missed something here.

> what I am trying to say is: replacing datetime64 isn't enough .. if we only had had a need for some "timestamp" type, we would never have added numpy, but just used plain python stdlib ...

Seems to be enough to [get crossbar working without numpy](https://github.com/crossbario/crossbar/compare/master...jameshilliard:datetime64), unless I've missed something important. The timestamp functionality seems to be the only reason numpy is a hard dependency based on my testing so far.

> Btw: similar discussions can be had over Flatbuffers vs X or Y, and LMDB vs A or B. That's perfectly fine, and there are very good X, Y and A, B, no question, it all depends. For crossbar, Flatbuffers+LMDB+Numpy is perfect in what crossbar needs, but of course there is a price.

I don't see any issues with flatbuffers or lmdb, I'm just confused why it appears that numpy is being pulled in as a hard dependency when it appears to only be needed for `datetime64`(which is easy enough to swap out for a pure python variant).

**Pull request closed without merging**
