### PR TITLE
Remove py2

### PR DESCRIPTION
**Pull request by om26er**
* Completely remove six
* All `from _future__ import ...` lines
* Removes Py2 CI
* Add Py38 CI

### CODE REVIEW

**Comment by om26er** [comment]
Ok, that is a genuine test failure on PyPy https://travis-ci.org/crossbario/zlmdb/jobs/639576741?utm_medium=notification&utm_source=github_status

**Comment by om26er** [comment]
That is indeed a flaky test, this time it passed on PyPy but failed on Py38 https://travis-ci.org/crossbario/zlmdb/jobs/639587320?utm_medium=notification&utm_source=github_status

**Comment by oberstet** [comment]
the problem is that the filling with test data here https://github.com/crossbario/zlmdb/blob/master/zlmdb/tests/test_select.py#L68 can lead to multiple situations where one or more of the randomized values is actually equal to the types default value - eg 0 for any number types.

this is the reason why the test have lines like:

```
assert len(data) in [528, 536, 544]
```

https://github.com/crossbario/zlmdb/blob/master/zlmdb/tests/test_select.py#L155

and

```
 AssertionError: assert 520 in [528, 536, 544]
```

with a newly encountered length of 520, where apparently multiple of the randomized values happened to be 0 (or default value in general) by accident.

we could also remove the value 0 from the randomization ..

**Comment by om26er** [comment]
> we could also remove the value 0 from the randomization ..

Would this work and is acceptable ?
```
diff --git a/zlmdb/tests/test_select.py b/zlmdb/tests/test_select.py
index 8e0cf2a..74af884 100644
--- a/zlmdb/tests/test_select.py
+++ b/zlmdb/tests/test_select.py
@@ -64,22 +64,22 @@ def rfloat():
 
 def fill_mnodelog(obj):
 
-    obj.timestamp = np.datetime64(time_ns(), 'ns') + np.timedelta64(random.randint(0, 120), 's')
+    obj.timestamp = np.datetime64(time_ns(), 'ns') + np.timedelta64(random.randint(1, 120), 's')
     obj.node_id = uuid.uuid4()
     obj.run_id = uuid.uuid4()
-    obj.state = random.randint(0, 2)
-    obj.ended = obj.timestamp + np.timedelta64(random.randint(0, 120), 's')
-    obj.session = random.randint(0, 9007199254740992)
+    obj.state = random.randint(1, 2)
+    obj.ended = obj.timestamp + np.timedelta64(random.randint(1, 120), 's')
+    obj.session = random.randint(1, 9007199254740992)
     obj.sent = obj.timestamp
-    obj.seq = random.randint(0, 10000)
+    obj.seq = random.randint(1, 10000)
 
-    obj.routers = random.randint(0, 32)
-    obj.containers = random.randint(0, 32)
-    obj.guests = random.randint(0, 32)
-    obj.proxies = random.randint(0, 32)
-    obj.marketmakers = random.randint(0, 32)
+    obj.routers = random.randint(1, 32)
+    obj.containers = random.randint(1, 32)
+    obj.guests = random.randint(1, 32)
+    obj.proxies = random.randint(1, 32)
+    obj.marketmakers = random.randint(1, 32)
 
-    obj.cpu_ctx_switches = random.randint(0, 1000000)
+    obj.cpu_ctx_switches = random.randint(1, 1000000)
 
     # we can't just use random() here, since it won't work for roundtrip
     # data checking (eg 33.42830630594208 != 33.428306579589844)
@@ -89,51 +89,51 @@ def fill_mnodelog(obj):
     obj.cpu_guest = rfloat()
     obj.cpu_guest_nice = rfloat()
     obj.cpu_idle = rfloat()
-    obj.cpu_interrupts = random.randint(0, 100000)
+    obj.cpu_interrupts = random.randint(1, 100000)
     obj.cpu_iotwait = rfloat()
     obj.cpu_irq = rfloat()
     obj.cpu_nice = rfloat()
-    obj.cpu_soft_interrupts = random.randint(0, 100000)
+    obj.cpu_soft_interrupts = random.randint(1, 100000)
     obj.cpu_softirq = rfloat()
     obj.cpu_steal = rfloat()
     obj.cpu_system = rfloat()
     obj.cpu_user = rfloat()
 
-    obj.network_bytes_recv = random.randint(0, 2**32)
-    obj.network_bytes_sent = random.randint(0, 2**32)
-    obj.network_connection_af_inet = random.randint(0, 1000)
-    obj.network_connection_af_inet6 = random.randint(0, 1000)
-    obj.network_connection_af_unix = random.randint(0, 1000)
-    obj.network_dropin = random.randint(0, 10000)
-    obj.network_dropout = random.randint(0, 10000)
-    obj.network_errin = random.randint(0, 10000)
-    obj.network_errout = random.randint(0, 10000)
-    obj.network_packets_recv = random.randint(0, 2**32)
-    obj.network_packets_sent = random.randint(0, 2**32)
+    obj.network_bytes_recv = random.randint(1, 2**32)
+    obj.network_bytes_sent = random.randint(1, 2**32)
+    obj.network_connection_af_inet = random.randint(1, 1000)
+    obj.network_connection_af_inet6 = random.randint(1, 1000)
+    obj.network_connection_af_unix = random.randint(1, 1000)
+    obj.network_dropin = random.randint(1, 10000)
+    obj.network_dropout = random.randint(1, 10000)
+    obj.network_errin = random.randint(1, 10000)
+    obj.network_errout = random.randint(1, 10000)
+    obj.network_packets_recv = random.randint(1, 2**32)
+    obj.network_packets_sent = random.randint(1, 2**32)
 
     M = 32 * 2**30
-    obj.memory_active = random.randint(0, M)
-    obj.memory_available = random.randint(0, M)
-    obj.memory_buffers = random.randint(0, M)
-    obj.memory_cached = random.randint(0, M)
-    obj.memory_free = random.randint(0, M)
-    obj.memory_inactive = random.randint(0, M)
+    obj.memory_active = random.randint(1, M)
+    obj.memory_available = random.randint(1, M)
+    obj.memory_buffers = random.randint(1, M)
+    obj.memory_cached = random.randint(1, M)
+    obj.memory_free = random.randint(1, M)
+    obj.memory_inactive = random.randint(1, M)
     obj.memory_percent = rfloat()
-    obj.memory_shared = random.randint(0, M)
-    obj.memory_slab = random.randint(0, M)
-    obj.memory_total = random.randint(0, M)
-    obj.memory_used = random.randint(0, M)
+    obj.memory_shared = random.randint(1, M)
+    obj.memory_slab = random.randint(1, M)
+    obj.memory_total = random.randint(1, M)
+    obj.memory_used = random.randint(1, M)
 
     M = 10 * 10
-    obj.disk_busy_time = random.randint(0, M)
-    obj.disk_read_bytes = random.randint(0, M)
-    obj.disk_read_count = random.randint(0, M)
-    obj.disk_read_merged_count = random.randint(0, M)
-    obj.disk_read_time = random.randint(0, M)
-    obj.disk_write_bytes = random.randint(0, M)
-    obj.disk_write_count = random.randint(0, M)
-    obj.disk_write_merged_count = random.randint(0, M)
-    obj.disk_write_time = random.randint(0, M)
+    obj.disk_busy_time = random.randint(1, M)
+    obj.disk_read_bytes = random.randint(1, M)
+    obj.disk_read_count = random.randint(1, M)
+    obj.disk_read_merged_count = random.randint(1, M)
+    obj.disk_read_time = random.randint(1, M)
+    obj.disk_write_bytes = random.randint(1, M)
+    obj.disk_write_count = random.randint(1, M)
+    obj.disk_write_merged_count = random.randint(1, M)
+    obj.disk_write_time = random.randint(1, M)
 
 
 @pytest.fixture(scope='function')
```

**Comment by oberstet** [comment]
yeah, lets go with that and merge it (you should also be able to reduce the asset to probably `assert len(data) == 544` .. because it now should never cut corners and always result in the full sized serialized bytes)

**Comment by om26er** [comment]
> yeah, lets go with that and merge it (you should also be able to reduce the asset to probably `assert len(data) == 544` .. because it now should never cut corners and always result in the full sized serialized bytes)

All done and CI is happy now.

**Pull request merged**
